package com.pacepal.walk.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pacepal.walk.data.vo.EventInfo;
import com.pacepal.walk.data.vo.StepInfo;

import com.pacepal.walk.data.dao.EventInfoDao;
import com.pacepal.walk.data.dao.StepInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventInfoDaoConfig;
    private final DaoConfig stepInfoDaoConfig;

    private final EventInfoDao eventInfoDao;
    private final StepInfoDao stepInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventInfoDaoConfig = daoConfigMap.get(EventInfoDao.class).clone();
        eventInfoDaoConfig.initIdentityScope(type);

        stepInfoDaoConfig = daoConfigMap.get(StepInfoDao.class).clone();
        stepInfoDaoConfig.initIdentityScope(type);

        eventInfoDao = new EventInfoDao(eventInfoDaoConfig, this);
        stepInfoDao = new StepInfoDao(stepInfoDaoConfig, this);

        registerDao(EventInfo.class, eventInfoDao);
        registerDao(StepInfo.class, stepInfoDao);
    }
    
    public void clear() {
        eventInfoDaoConfig.clearIdentityScope();
        stepInfoDaoConfig.clearIdentityScope();
    }

    public EventInfoDao getEventInfoDao() {
        return eventInfoDao;
    }

    public StepInfoDao getStepInfoDao() {
        return stepInfoDao;
    }

}
